-- MySQL Script generated by MySQL Workbench
-- Thu Oct 30 23:40:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pawpal_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pawpal_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pawpal_system` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci ;
USE `pawpal_system` ;

-- -----------------------------------------------------
-- Table `pawpal_system`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pawpal_system`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password_hash` VARCHAR(255) NULL DEFAULT NULL,
  `phone_number` VARCHAR(50) NULL DEFAULT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(100) NULL DEFAULT NULL,
  `state` VARCHAR(100) NULL DEFAULT NULL,
  `zip_code` VARCHAR(20) NULL DEFAULT NULL,
  `about_me` TEXT NULL DEFAULT NULL,
  `role` ENUM('user', 'admin') NULL DEFAULT 'user',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pawpal_system`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pawpal_system`.`admins` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`admin_id`),
  INDEX `user_id` (`user_id`),
  CONSTRAINT `admins_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `pawpal_system`.`users` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pawpal_system`.`shelters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pawpal_system`.`shelters` (
  `shelter_id` INT NOT NULL AUTO_INCREMENT,
  `admin_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(50) NULL DEFAULT NULL,
  `working_days` VARCHAR(255) NULL DEFAULT NULL,
  `working_hours` VARCHAR(255) NULL DEFAULT NULL,
  `dog_count` INT NULL DEFAULT '0',
  `cat_count` INT NULL DEFAULT '0',
  `other_count` INT NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`shelter_id`),
  INDEX `admin_id` (`admin_id`),
  CONSTRAINT `shelters_ibfk_1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `pawpal_system`.`admins` (`admin_id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pawpal_system`.`pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pawpal_system`.`pets` (
  `pet_id` INT NOT NULL AUTO_INCREMENT,
  `shelter_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `type` ENUM('dog', 'cat', 'other') NULL DEFAULT NULL,
  `age` INT NULL DEFAULT NULL,
  `size` ENUM('small', 'medium', 'large') NULL DEFAULT NULL,
  `gender` ENUM('male', 'female', 'unknown') NULL DEFAULT NULL,
  `availability` ENUM('available', 'pending', 'adopted') NULL DEFAULT 'available',
  `about` TEXT NULL DEFAULT NULL,
  `characteristics` TEXT NULL DEFAULT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`pet_id`),
  INDEX `shelter_id` (`shelter_id`),
  CONSTRAINT `pets_ibfk_1`
    FOREIGN KEY (`shelter_id`)
    REFERENCES `pawpal_system`.`shelters` (`shelter_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pawpal_system`.`adoption_requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pawpal_system`.`adoption_requests` (
  `request_id` INT NOT NULL AUTO_INCREMENT,
  `pet_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `admin_id` INT NULL DEFAULT NULL,
  `status` ENUM('pending', 'approved', 'rejected') NULL DEFAULT 'pending',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `processed_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`request_id`),
  INDEX `pet_id` (`pet_id`),
  INDEX `user_id` (`user_id`),
  INDEX `admin_id` (`admin_id`),
  CONSTRAINT `adoption_requests_ibfk_1`
    FOREIGN KEY (`pet_id`)
    REFERENCES `pawpal_system`.`pets` (`pet_id`)
    ON DELETE CASCADE,
  CONSTRAINT `adoption_requests_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `pawpal_system`.`users` (`user_id`)
    ON DELETE CASCADE,
  CONSTRAINT `adoption_requests_ibfk_3`
    FOREIGN KEY (`admin_id`)
    REFERENCES `pawpal_system`.`admins` (`admin_id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pawpal_system`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pawpal_system`.`reviews` (
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `shelter_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `rating` INT NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`review_id`),
  INDEX `shelter_id` (`shelter_id`),
  INDEX `user_id` (`user_id`),
  CONSTRAINT `reviews_ibfk_1`
    FOREIGN KEY (`shelter_id`)
    REFERENCES `pawpal_system`.`shelters` (`shelter_id`)
    ON DELETE CASCADE,
  CONSTRAINT `reviews_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `pawpal_system`.`users` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
